# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with o/r without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Build the Hyrax Server
# Build the code for test coverage analysis
# jhrg 11/17/20
# sbl   9/30/22

all:
#	current_dir="$(shell pwd)"
#	current_dir+="/build"
#	$(info    current_dir is ${current_dir})
#	(cd hyrax-dependencies && ${MAKE} prefix=${current_dir})
	(cd libdap4 && ${MAKE})
	(cd bes && ${MAKE})

check:
	(cd libdap4 && ${MAKE} check)
	(cd bes && ${MAKE} check)
